### ISSUE TITLE
OSError: the file is not EDF(+) or BDF(+) compliant (Physical Maximum)

### ISSUE THREAD

**Issue by ezeid** [holgern/pyedflib#113]
Hi,

I am processing a list of .edf files and for a quite a few of them I am receiving the following error:
"the file is not EDF(+) or BDF(+) compliant (Physical Maximum)"

Is there a solution for this? Can something be made?

Thank you
Elias

**Comment by skjerns** [comment]
This usually says that the header information has been written incorrectly by the producing system. It is possible to fix these manually, or using the EDFBrowser header editor (under tools->header editor -> just save copy). Right now there is unfortunately no automated way to fix wrong header information

**Comment by ezeid** [comment]
When I try to open one of the problematic edf file in EDFBrowser I get the error: "Physical maximum of signal 34 is equal to physical minimum File is not a valid EDF or BDF File". Next, I open it in header editor, I see "Header" and 'Signals' (see atatched) tabs but no clue where I can fix the 'physical maximum' value of channel 34.

![EDF_issue1](https://user-images.githubusercontent.com/71358531/108573694-4a9edd00-72e3-11eb-9f8d-f0db94769c6c.jpg)
![EDF_issue2](https://user-images.githubusercontent.com/71358531/108573695-4a9edd00-72e3-11eb-9d13-a51e538f7964.jpg)

**Comment by skjerns** [comment]
Just try clicking "save" again and opening the file again, that might work.


According to the EDF specifications, the digital minimum must be different from the digital maximum (could be to avoid zero division)

**Comment by AlexLepauvre** [comment]
Dear all,

I am facing a similar issue though I am attempting to do something slightly different. I am using the pyedflib to first load an EDF file. In one of the channel, we have photodiode triggers. For a specific project, we are required to chop up the EDF file according to specific photodiode triggers patterns. From one EDF file we generate 5 sub EDF files. 

The photodiode signal is read in. Then, the samples at which to cut are computed based on the photodiode triggers. The part of the original signal to save to a new file is then read in digitally and written to a new file.   

The issue I am facing is that when loading the original signal all is well, but the sub-files that are getting saved give me the same described error. I am therefore wondering if the issue lies in the fact that the physical max and min are taken from the whole file and do not get adjusted to the smaller file. In other words, my question is does the functionalities of pyedflib to write edf files automatically compute the physical max and min of the signal to be saved or whether it needs to be computed separately?

Thanks a lot for the support,

Kind regards,

Alex

P.S.: I unfortunately cannot share the files in question due to data privacy issues. I can however share the repo of the code if that helps.

**Comment by skjerns** [comment]
Depends on which function you use. You can specify the min/max of the signals inside the `signal_headers` sobject that you pass to the write function.

best practice would be to just take the header object that you get from `read_edf` and pass it along to `write_edf` - also make sure that the min/max of the channel are not the same (see above). 

Please also post a minimal working example code, else I don't really know what functions you are using, and where it might go wrong. Additionally also post the contents of the signal_headers of the original file and/or of the newly saved files.

**Comment by AlexLepauvre** [comment]
Dear Skjerns, 

Here is a working version of my code (the actual is embedded in a larger script as it is a GUI we use in our lab):
`
# Opening in the original file
edf_file_handle = pyedflib.EdfReader(self.edf_file, 0, 0)

# Get the different headers from the original file
orig_srate = edf_file_handle.getSampleFrequency(1)
orig_start_time = edf_file_handle.getStartdatetime()
orig_electrodes = edf_file_handle.getSignalLabels()
orig_n_electrodes = len(orig_electrodes)

# Compute onset sample (This is just for the sake of the example, it is more complex in the original script):
onset_sample = 0
offset_sample = 10000

# Computing the number of chunks when cutting the present segment in 1 sec chunks:
nb_blocks = np.ceil((offset_sample - onset_sample) / orig_srate).astype('int32')
# Adjusting the offset to be a multiple of the number of blocks by displacing it towards the end
 offset_sample = 0 + nb_blocks * orig_srate

# Opening the new file:
o = pyedflib.EdfWriter('New_file.EDF', orig_n_electrodes)

# -----------------------------------------------------------------------------------------
# Setting the headers
# Fetching the headers of the original file
o.setHeader(edf_file_handle.getHeader())
# Setting the signal headers according to the original file:
o.setSignalHeaders([edf_file_handle.getSignalHeaders()[i] for i in range(orig_n_electrodes)])
o.update_header()
# Adjusting start time based on where we cut:
s = round(onset_sample / orig_srate)
new_starttime = orig_start_time + datetime.timedelta(0, s)
o.setStartdatetime(new_starttime)
o.update_header()


# -----------------------------------------------------------------------------------------
# Saving the file
# Creating the signal buffer that will hold the loaded digital values
sigbuf = np.zeros((orig_n_electrodes, orig_srate), dtype=np.int32),
# Saving the file:
for kk in range(nb_blocks):
    # Getting the starting sample of the current block:
    c_start = onset_sample + (kk * orig_srate)
    # Looping through all the electrodes:
    for cc in range(len(orig_electrodes)):
        # sigbuf is a reference argument
        edf_file_handle.read_digital_signal(cc, c_start, orig_srate, sigbuf[cc, :])
    # Writing the blocks to the newly created file:
    o.writeSamples(sigbuf, digital=True)
# Updating the file header:
o.update_header()
# Closing the newly created file:
o.close()
`

Here are the signal headers of the original file:
{'label': 'A1', 'dimension': 'uV', 'sample_rate': 2048, 'physical_max': -8711.0, 'physical_min': 8711.0, 'digital_max': 32767, 'digital_min': -32768, 'prefilter': '', 'transducer': ''}

I tried to open the headers of the signal with pyedflib but it failed due to the issue. I then tried to open the signal in EDF browser, and here is the error I get:
![image](https://user-images.githubusercontent.com/54275933/115761011-2a060880-a3a2-11eb-8cec-e436d705419a.png)

I also opened the headers editor of edfbrowser and here is what it looks like:
![image](https://user-images.githubusercontent.com/54275933/115761147-515cd580-a3a2-11eb-9003-1e53a9c2a848.png)

Note that this is an issue I am facing only for the specific file. I have been able to use the script provided above for 6 different EDF files and it worked fine. A colleague of mine also used it but no success, getting the same error I am now getting. 

From the error of edfbrowser, it looks like for the signal headers, the max and min are empty, perhaps this is the problem?

Thanks in advance for your support,

Kind regards,

Alex

**Comment by skjerns** [comment]
I don't really know what the problem could be. Can you try using the functions present in `pyedflib.highlevel`, e.g. `pyedflib.highlevel.read_edf` and `pyedflib.highlevel.write_edf` ? There is some error catching being done there, maybe it will help.

Else without a sample file I really don't know what this could be. 

Can you send me the raw ASCII header of the corrupt file? (e.g. open it with `notepad` and copy paste the first line, i.e. until it becomes unintelligible)

**Comment by AlexLepauvre** [comment]
Dear Skjerns,

I believe I found the issue that was causing the error. One difference between the file I was trying to save and the one I previously successfully saved was the presence of channels with very specific headers. These channels are called "Trig", "OSAT", "PR" and "Pleth". These channels had very weird signal headers (unit: % for example) in the original file, and when these channels are saved to another files, they cause further issues in the new file signal headers (see attached .txt file), inducing the presence of spurious characters. I am therefore guessing that the issue occurs somewhere in EdfWriter and/or setSignalHeaders. 

Fortunately, these channels are not required for my analysis. I am still in the process of figuring out what they are with the RA and why they were found in my signal, I will let you know as soon as I have figured it out. For my specific purpose, I added a statement to remove these channels if they are found in the original file. 

Would you like me to give you more information about these channels and the reason behind the bug to eventually address it, or should we just close this issue (either ways are fine by me as I don't need these channels anyways)?
[wrong_headers.txt](https://github.com/holgern/pyedflib/files/6493086/wrong_headers.txt)

Thanks a lot for the support,

Kind regards,

Alex

**Comment by warren-manuel** [comment]
Hello, 

Didin't want to open a new issue to something quite similar. My header file contains a unsupported symbol (°) and I can't seem to open the file once changing it. (I am trying to replicate what edfbrowser's header editor does)
I'm quite sure it's an issue with the encoding but unsure how to proceed further. 
The OSError that I get is : `the file is not EDF(+) or BDF(+) compliant (Filesize)`

**Comment by skjerns** [comment]
You need to make sure to open and save the file in binary mode. If you save it as ASCII or UTF8 it will not be recognized any longer.

Additionally, you need to make sure not to delete the symbol but replace it, such that the header size stays the same.

Hope that helps!

-----------
Sent from mobile

**Comment by TomMingasson** [comment]
> Hello,
> 
> Didin't want to open a new issue to something quite similar. My header file contains a unsupported symbol (°) and I can't seem to open the file once changing it. (I am trying to replicate what edfbrowser's header editor does) I'm quite sure it's an issue with the encoding but unsure how to proceed further. The OSError that I get is : `the file is not EDF(+) or BDF(+) compliant (Filesize)`

Hi @warren-manuel, 
did you find a way to fix the invalid header "not manually" ? as I have thousands of EDF to fix..
thanks :)
