### ISSUE TITLE
Saving to EDF with no precision loss

### ISSUE THREAD

**Issue by PhlipPhlops** [holgern/pyedflib#122]
I'm using this script to save an MNE Raw to EDF, and it leverages pyedflib
https://gist.github.com/skjerns/bc660ef59dca0dbd53f00ed38c42f6be

What I've noticed is that any EDF file can be loaded by MNE's read_raw_edf() method, then save back to EDF using the above script with no loss.
I've verified this losslessness by using Numpy's array compare; data before the save is perfectly equal to data after the save.

However, trying to load up a Nihon Koden .EEG filetype using MNE's read_raw_nihon() method, then saving that Raw to EDF using this script, results in intolerable loss in precision. Numpy's array compare shows that exactly 0 of the elements in the array after the save are equal to the array before the save.

I could use help thinking through this problem and perhaps modifying this script to accommodate. Is there a way using pyedflib to save this data losslessly?

**Comment by skjerns** [comment]
Dear @PhlipPhlops this is due to the implementation of EDF. Internally, EDF is stored as a INT16 stream, and then converted to float via the fields `physical_min` and `physical_max`. This means that EDF is not able to store all range of values.

If you load an EDF, and use the exact same header values, then of course the exact same values can be displayed. If loading other data formats this might not be case.

Unfortunately, this problem is inherent to the EDF+ standard. What you can do is use BDF instead (it has 24-bit precision instead of 16-bit), or play around with the physical min/max fields to increase precision. Also upscaling to a different voltage dimension (storing mV instead of V) can help increase precision.

I hope that clarifies the problem a bit, let me know if you have any questions
